### ISSUE TITLE
Unable to run in Fedora 23

### ISSUE THREAD

**Issue by urbenlegend** [RobertBeckebans/RBDOOM-3-BFG#259]
I've tried compiling the latest master on Fedora 23 and it consistently crashes on startup with the following message:

```
QA Timing INIT: 000878ms
RBDOOM 3 BFG 1.0.3.1401 linux-x86_86 Nov 30 2015 17:28:27
found interface lo - loopback
found interface wlp3s0 - 192.168.1.38/255.255.255.0
found interface virbr0 - 192.168.124.1/255.255.255.0
------ Initializing File System ------
signal caught: Segmentation fault
si_code 1
Trying to exit gracefully..
session->GetSaveGameManager().CancelToTerminate();
soundSystem->StopAllSounds();
Stop();
--------- Game Map Shutdown ----------
--------------------------------------
CleanupShell();
delete loadGUI;
delete renderWorld;
delete soundWorld;
delete menuSoundWorld;
session->ShutdownSoundRelatedSystems();
session->Shutdown();
game->Leaderboards_Shutdown();
uiManager->Shutdown();
soundSystem->Shutdown();
usercmdGen->Shutdown();
eventLoop->Shutdown();
declManager->Shutdown();
renderSystem->Shutdown();
idRenderSystem::Shutdown()
double fault Segmentation fault, bailing out
```

**Comment by spannerman79** [comment]
SELinux off?

**Comment by urbenlegend** [comment]
I tried with SELinux permissive mode and it still crashes.

**Comment by spannerman79** [comment]
Permissive still enforces DAC rules.  to be honest I do not know enough about the code behind this or what might cause it, I just know from experience that SELinux is more of a pain in the .... on a desktop system then what its worth.

**Comment by DanielGibson** [comment]
A backtrace would be nice.

Run it in gdb like this (in the shell): `gdb ./RBDoom3BFG`
in gdb enter `run` to start the game

and when it crashes enter `backtrace`
(enter `quit` to leave gdb again afterwards).

**Comment by urbenlegend** [comment]
Here's the gdb trace:

```
#0  idStrStatic<256>::idStrStatic (this=0x138) at idlib/../idlib/StrStatic.h:51
#1  idResourceCacheEntry::idResourceCacheEntry (this=0x138) at idlib/../framework/File_Resource.h:44
#2  idListArrayNew<idResourceCacheEntry, (memTag_t)103> (zeroBuffer=false, num=83886080) at idlib/../idlib/containers/List.h:62
#3  idListArrayResize<idResourceCacheEntry, (memTag_t)103> (zeroBuffer=false, newNum=83886080, oldNum=0, voldptr=0x0) at idlib/../idlib/containers/List.h:95
#4  idList<idResourceCacheEntry, (memTag_t)103>::Resize (newsize=83886080, this=0x33e3de0) at idlib/../idlib/containers/List.h:472
#5  idList<idResourceCacheEntry, (memTag_t)103>::SetNum (newnum=83886080, this=0x33e3de0) at idlib/../idlib/containers/List.h:378
#6  idResourceContainer::Init (this=this@entry=0x33e3ca0, _fileName=<optimized out>, containerIndex=0 '\000') at /home/benxiao/bin/RBDOOM-3-BFG/neo/framework/File_Resource.cpp:94
#7  0x00000000005f0349 in idFileSystemLocal::AddGameDirectory (this=0x10f1c20 <fileSystemLocal>, path=0x33e3240 "/home/benxiao/bin/RBDOOM-3-BFG", dir=dir@entry=0xd8345e "base")
    at /home/benxiao/bin/RBDOOM-3-BFG/neo/framework/FileSystem.cpp:3003
#8  0x00000000005f0818 in idFileSystemLocal::SetupGameDirectories (this=this@entry=0x10f1c20 <fileSystemLocal>, gameName=gameName@entry=0xd8345e "base")
    at /home/benxiao/bin/RBDOOM-3-BFG/neo/framework/FileSystem.cpp:3027
#9  0x00000000005f0864 in idFileSystemLocal::Startup (this=this@entry=0x10f1c20 <fileSystemLocal>) at /home/benxiao/bin/RBDOOM-3-BFG/neo/framework/FileSystem.cpp:3076
#10 0x00000000005f0b56 in idFileSystemLocal::Init (this=0x10f1c20 <fileSystemLocal>) at /home/benxiao/bin/RBDOOM-3-BFG/neo/framework/FileSystem.cpp:3144
#11 0x000000000060dda8 in idCommonLocal::Init (this=0x1107640 <commonLocal>, argc=0, argv=<optimized out>, cmdline=<optimized out>) at /home/benxiao/bin/RBDOOM-3-BFG/neo/framework/Common.cpp:1217
#12 0x00000000005a2468 in main (argc=1, argv=0x7fffffffdf48) at /home/benxiao/bin/RBDOOM-3-BFG/neo/sys/posix/platform_linux.cpp:537
```

**Comment by ebkalderon** [comment]
Bump. Any word on this? I am also getting similar output in Arch Linux.

**Comment by urbenlegend** [comment]
Here's the gdb trace when compiling in debug mode:

```
#0  0x000000000062dc23 in idStr::SetStatic (this=0x8b00000145, isStatic=false) at idlib/../idlib/Str.h:393
#1  0x000000000062dc5f in idStr::Construct (this=0x8b00000145) at idlib/../idlib/Str.h:435
#2  0x000000000062dd2e in idStr::idStr (this=0x8b00000145) at idlib/../idlib/Str.h:477
#3  0x0000000000677a2b in idStrStatic<256>::idStrStatic (this=0x8b00000145) at idlib/../idlib/StrStatic.h:51
#4  0x0000000000676fa1 in idResourceCacheEntry::idResourceCacheEntry (this=0x8b00000145) at idlib/../framework/File_Resource.h:44
#5  0x00000000006c84cf in idListArrayNew<idResourceCacheEntry, (memTag_t)103> (num=83886080, zeroBuffer=false) at idlib/../idlib/containers/List.h:62
#6  0x00000000006c83bd in idListArrayResize<idResourceCacheEntry, (memTag_t)103> (voldptr=0x0, oldNum=0, newNum=83886080, zeroBuffer=false) at idlib/../idlib/containers/List.h:95
#7  0x00000000006c8348 in idList<idResourceCacheEntry, (memTag_t)103>::Resize (this=0x350c350, newsize=83886080) at idlib/../idlib/containers/List.h:472
#8  0x00000000006c8112 in idList<idResourceCacheEntry, (memTag_t)103>::SetNum (this=0x350c350, newnum=83886080) at idlib/../idlib/containers/List.h:378
#9  0x00000000006c6328 in idResourceContainer::Init (this=0x350c210, _fileName=0x350bdd0 "_common.resources", containerIndex=0 '\000')
    at /home/benxiao/bin/RBDOOM-3-BFG/neo/framework/File_Resource.cpp:94
#10 0x00000000006731b4 in idFileSystemLocal::AddGameDirectory (this=0x12183a0 <fileSystemLocal>, path=0x350b7b0 "/home/benxiao/bin/RBDOOM-3-BFG", dir=0xd3d924 "base")
    at /home/benxiao/bin/RBDOOM-3-BFG/neo/framework/FileSystem.cpp:3003
#11 0x00000000006732dc in idFileSystemLocal::SetupGameDirectories (this=0x12183a0 <fileSystemLocal>, gameName=0xd3d924 "base") at /home/benxiao/bin/RBDOOM-3-BFG/neo/framework/FileSystem.cpp:3027
#12 0x00000000006733c1 in idFileSystemLocal::Startup (this=0x12183a0 <fileSystemLocal>) at /home/benxiao/bin/RBDOOM-3-BFG/neo/framework/FileSystem.cpp:3076
#13 0x0000000000673838 in idFileSystemLocal::Init (this=0x12183a0 <fileSystemLocal>) at /home/benxiao/bin/RBDOOM-3-BFG/neo/framework/FileSystem.cpp:3144
#14 0x000000000068dd60 in idCommonLocal::Init (this=0x1219980 <commonLocal>, argc=0, argv=0x0, cmdline=0x0) at /home/benxiao/bin/RBDOOM-3-BFG/neo/framework/Common.cpp:1217
#15 0x0000000000c541ef in main (argc=1, argv=0x7fffffffe008) at /home/benxiao/bin/RBDOOM-3-BFG/neo/sys/posix/platform_linux.cpp:537
```

**Comment by urbenlegend** [comment]
Well crap. After a few hours of debugging this myself in Eclipse, I finally thought "Maybe the game files are corrupted or improperly downloaded..."

So I booted into my Windows partition and downloaded the game files from there, copied them over to my Linux install and voila! It works!

It seems like the download method using the Steam Console does NOT work. You either need to download the game files via Wine or with a Windows install. We should probably remove this from the README or fix that command somehow. @ebkalderon can you confirm this on your system?

**Comment by ebkalderon** [comment]
Indeed, I tried again by downloading the game files with Steam on PlayOnLinux, and it works fine now. I affirm @urbenlegend's suggestion; please either revise or remove the Steam Console method from the README.

**Comment by DanielGibson** [comment]
Oh right, I already noticed with dhewm3 that Steam console download is 
broken, should have created a pull request for rbd3bfg for a changed 
README, sorry :-/

It can still be done without wine or windows, using steamcmd, see
https://github.com/dhewm/dhewm3/wiki/FAQ#how-do-i-get-the-files-using-steam

**Comment by DanielGibson** [comment]
as #260 is merged, I guess this can be closed.
Or do @urbenlegend and @ebkalderon test the steamcmd instructions first?
