### ISSUE TITLE
[vulkan] Segfault upon quitting game

### ISSUE THREAD

**Issue by runlevel5** [RobertBeckebans/RBDOOM-3-BFG#539]
### Info

```
$ uname -ar
Linux localhost.localdomain 5.10.24-200.fc33.ppc64le #1 SMP Thu Mar 18 12:17:15 AEDT 2021 ppc64le ppc64le ppc64le GNU/Linux

$ gcc --version
gcc (GCC) 10.2.1 20201125 (Red Hat 10.2.1-9)

$ cmake -G "Unix Makefiles" -DONATIVE=YES -DCMAKE_BUILD_TYPE=Debug -DSDL2=ON -DUSE_VULKAN=ON -DSPIRV_SHADERC=OFF ../neo
```

everytime I quit the game, the game gets segfault. 

### Stacktrace

```
0x0653070f05960148 in ?? ()
(gdb) bt 1000
#0  0x0653070f05960148 in  ()
#1  0x00007ffff7ecc4b8 in vkDestroyBuffer (device=0x143d4bf0, buffer=0x14837890, pAllocator=0x0)
    at ../loader/trampoline.c:1169
#2  0x0000000010deb550 in vmaDestroyBuffer(VmaAllocator_T*, VkBuffer_T*, VmaAllocation_T*)
    (allocator=0x143c8c50, buffer=0x14837890, allocation=0x14874a40)
    at /home/tle/src/RBDOOM-3-BFG/neo/renderer/Vulkan/vma.h:5526
#3  0x0000000010dc1ad0 in idVertexBuffer::FreeBufferObject() (this=0x11d23ea0 <vertexCache+96>)
    at /home/tle/src/RBDOOM-3-BFG/neo/renderer/Vulkan/BufferObject_VK.cpp:179
#4  0x000000001053ed28 in idVertexBuffer::~idVertexBuffer()
    (this=0x11d23ea0 <vertexCache+96>, __in_chrg=<optimized out>)
    at /home/tle/src/RBDOOM-3-BFG/neo/renderer/BufferObject.cpp:158
#5  0x0000000010640394 in geoBufferSet_t::~geoBufferSet_t()
    (this=0x11d23e50 <vertexCache+16>, __in_chrg=<optimized out>)
    at /home/tle/src/RBDOOM-3-BFG/neo/idlib/../renderer/VertexCache.h:96
#6  0x000000001064053c in idVertexCache::~idVertexCache()
    (this=0x11d23e40 <vertexCache>, __in_chrg=<optimized out>)
    at /home/tle/src/RBDOOM-3-BFG/neo/idlib/../renderer/VertexCache.h:110
#7  0x00007ffff596c7d4 in __run_exit_handlers
    (status=<optimized out>, listp=0x7ffff5b30818 <__exit_funcs>, run_list_atexit=run_list_atexit@entry=true, run_dtors=run_dtors@entry=true) at exit.c:108
#8  0x00007ffff596ca18 in __GI_exit (status=<optimized out>) at exit.c:139
#9  0x0000000010da5404 in Posix_Exit(int) (ret=0)
    at /home/tle/src/RBDOOM-3-BFG/neo/sys/posix/posix_main.cpp:155
#10 0x0000000010da5630 in Sys_Quit() ()
    at /home/tle/src/RBDOOM-3-BFG/neo/sys/posix/posix_main.cpp:209
#11 0x000000001046fe74 in idCommonLocal::Quit() (this=0x11798ed0 <commonLocal>)
    at /home/tle/src/RBDOOM-3-BFG/neo/framework/Common.cpp:228
#12 0x0000000010bfeac0 in idMenuHandler_Shell::idSWFScriptFunction_QuitDialog::Call(idSWFScriptObject*, idSWFParmList const&) (this=0x143a9890, thisObject=0x19571ba0, parms=...)
    at /home/tle/src/RBDOOM-3-BFG/neo/d3xp/menus/MenuHandler_Shell.cpp:939
#13 0x0000000010892910 in idSWFScriptFunction_Script::Run(idSWFScriptObject*, idSWFStack&, idSWFBitStream&) (this=0x7ffe30116b80, thisObject=0x195e4100, stack=..., bitstream=...)
    at /home/tle/src/RBDOOM-3-BFG/neo/swf/SWF_ScriptFunction.cpp:1162
#14 0x000000001088e334 in idSWFScriptFunction_Script::Call(idSWFScriptObject*, idSWFParmList const&) (this=0x7ffe30116b80, thisObject=0x195e4100, parms=...)
    at /home/tle/src/RBDOOM-3-BFG/neo/swf/SWF_ScriptFunction.cpp:251
#15 0x0000000010856368 in idSWF::HandleEvent(sysEvent_t const*) (
    this=0x17a360a0, event=0x7fffffffe288) at /home/tle/src/RBDOOM-3-BFG/neo/swf/SWF_Events.cpp:367
#16 0x0000000010482024 in idCommonDialog::HandleDialogEvent(sysEvent_t const*)
    (this=0x11799fe8 <commonLocal+4376>, sev=0x7fffffffe288)
    at /home/tle/src/RBDOOM-3-BFG/neo/framework/Common_dialog.cpp:1569
#17 0x0000000010475ad0 in idCommonLocal::ProcessEvent(sysEvent_t const*)
    (this=0x11798ed0 <commonLocal>, event=0x7fffffffe288)
    at /home/tle/src/RBDOOM-3-BFG/neo/framework/Common.cpp:1847
#18 0x00000000104f58c8 in idEventLoop::ProcessEvent(sysEvent_t)
    (this=0x11a5f3a8 <eventLoopLocal>, ev=...)
    at /home/tle/src/RBDOOM-3-BFG/neo/framework/EventLoop.cpp:186
#19 0x00000000104f59e0 in idEventLoop::RunEventLoop(bool)
    (this=0x11a5f3a8 <eventLoopLocal>, commandExecution=true)
    at /home/tle/src/RBDOOM-3-BFG/neo/framework/EventLoop.cpp:221
#20 0x000000001053691c in idCommonLocal::Frame() (this=0x11798ed0 <commonLocal>)
    at /home/tle/src/RBDOOM-3-BFG/neo/framework/common_frame.cpp:537
#21 0x0000000010da520c in main(int, char const**) (argc=1, argv=0x7fffffffed08)
    at /home/tle/src/RBDOOM-3-BFG/neo/sys/posix/platform_linux.cpp:617
 ```

**Comment by RobertBeckebans** [comment]
Just update to the current master and try again, please.

**Comment by r-a-sattarov** [comment]
Maybe this PR https://github.com/RobertBeckebans/RBDOOM-3-BFG/pull/378 will fix it?

**Comment by runlevel5** [comment]
@RobertBeckebans I've just tried again with master branch:

```
--Type <RET> for more, q to quit, c to continue without paging--

Thread 1 "RBDoom3BFG" received signal SIGTRAP, Trace/breakpoint trap.
0x00007ffff7daa594 in __libc_signal_restore_set (set=0x7fffffffc668) at ../sysdeps/unix/sysv/linux/internal-signals.h:104
104	  INTERNAL_SYSCALL_CALL (rt_sigprocmask, SIG_SETMASK, set, NULL,
(gdb) bt 1000
#0  0x00007ffff7daa594 in __libc_signal_restore_set (set=0x7fffffffc668) at ../sysdeps/unix/sysv/linux/internal-signals.h:104
#1  raise (sig=<optimized out>) at ../sysdeps/unix/sysv/linux/raise.c:47
#2  0x0000000010da7404 in AssertFailed(char const*, int, char const*)
    (file=0x11199188 "/home/tle/src/RBDOOM-3-BFG/neo/idlib/../idlib/containers/StrPool.h", line=190, expression=0x111991d0 "poolStr->pool == this") at /home/tle/src/RBDOOM-3-BFG/neo/idlib/sys/sys_assert.cpp:106
#3  0x0000000010cccbe0 in idStrPool::FreeString(idPoolStr const*) (this=0x136b5438 <idDict::globalKeys>, poolStr=0x14ac5120)
    at /home/tle/src/RBDOOM-3-BFG/neo/idlib/../idlib/containers/StrPool.h:190
#4  0x0000000010cc88b4 in idDict::Clear() (this=0x118f4890 <sessionLocalWin+10368>) at /home/tle/src/RBDOOM-3-BFG/neo/idlib/Dict.cpp:233
#5  0x000000001030cf74 in idDict::~idDict() (this=0x118f4890 <sessionLocalWin+10368>, __in_chrg=<optimized out>)
    at /home/tle/src/RBDOOM-3-BFG/neo/idlib/../idlib/Dict.h:229
#6  0x000000001030ed14 in idMatchParameters::~idMatchParameters() (this=0x118f4860 <sessionLocalWin+10320>, __in_chrg=<optimized out>)
    at /home/tle/src/RBDOOM-3-BFG/neo/idlib/../framework/../sys/sys_session.h:121
#7  0x0000000010c82490 in idLobby::~idLobby() (this=0x118f34f0 <sessionLocalWin+5344>, __in_chrg=<optimized out>)
    at /home/tle/src/RBDOOM-3-BFG/neo/sys/sys_lobby.h:40
#8  0x0000000010c7080c in idSessionLocal::~idSessionLocal() (this=0x118f2010 <sessionLocalWin>, __in_chrg=<optimized out>)
    at /home/tle/src/RBDOOM-3-BFG/neo/sys/sys_session_local.cpp:140
#9  0x00000000107c80e8 in idSessionLocalWin::~idSessionLocalWin() (this=0x118f2010 <sessionLocalWin>, __in_chrg=<optimized out>)
    at /home/tle/src/RBDOOM-3-BFG/neo/sys/common/session_local.cpp:207
#10 0x00007ffff58fc7d4 in __run_exit_handlers
    (status=<optimized out>, listp=0x7ffff5ac0818 <__exit_funcs>, run_list_atexit=run_list_atexit@entry=true, run_dtors=run_dtors@entry=true) at exit.c:108
#11 0x00007ffff58fca18 in __GI_exit (status=<optimized out>) at exit.c:139
#12 0x0000000010c8ee20 in Posix_Exit(int) (ret=0) at /home/tle/src/RBDOOM-3-BFG/neo/sys/posix/posix_main.cpp:155
#13 0x0000000010c8f04c in Sys_Quit() () at /home/tle/src/RBDOOM-3-BFG/neo/sys/posix/posix_main.cpp:209
#14 0x0000000010305b54 in idCommonLocal::Quit() (this=0x11379d20 <commonLocal>) at /home/tle/src/RBDOOM-3-BFG/neo/framework/Common.cpp:228
#15 0x0000000010aea15c in idMenuHandler_Shell::idSWFScriptFunction_QuitDialog::Call(idSWFScriptObject*, idSWFParmList const&)
    (this=0x2dd71240, thisObject=0x17cd3730, parms=...) at /home/tle/src/RBDOOM-3-BFG/neo/d3xp/menus/MenuHandler_Shell.cpp:939
#16 0x0000000010782b4c in idSWFScriptFunction_Script::Run(idSWFScriptObject*, idSWFStack&, idSWFBitStream&)
    (this=0x7ffed4002500, thisObject=0x17d148a0, stack=..., bitstream=...)
    at /home/tle/src/RBDOOM-3-BFG/neo/swf/SWF_ScriptFunction.cpp:1162
#17 0x000000001077e570 in idSWFScriptFunction_Script::Call(idSWFScriptObject*, idSWFParmList const&)
    (this=0x7ffed4002500, thisObject=0x17d148a0, parms=...) at /home/tle/src/RBDOOM-3-BFG/neo/swf/SWF_ScriptFunction.cpp:251
#18 0x0000000010745920 in idSWF::HandleEvent(sysEvent_t const*) (this=0x1615a940, event=0x7fffffffe288)
    at /home/tle/src/RBDOOM-3-BFG/neo/swf/SWF_Events.cpp:285
--Type <RET> for more, q to quit, c to continue without paging--
#19 0x0000000010317d04 in idCommonDialog::HandleDialogEvent(sysEvent_t const*) (this=0x1137ae38 <commonLocal+4376>, sev=0x7fffffffe288)
    at /home/tle/src/RBDOOM-3-BFG/neo/framework/Common_dialog.cpp:1569
#20 0x000000001030b7b0 in idCommonLocal::ProcessEvent(sysEvent_t const*) (this=0x11379d20 <commonLocal>, event=0x7fffffffe288)
    at /home/tle/src/RBDOOM-3-BFG/neo/framework/Common.cpp:1847
#21 0x000000001038b5a8 in idEventLoop::ProcessEvent(sysEvent_t) (this=0x11640200 <eventLoopLocal>, ev=...)
    at /home/tle/src/RBDOOM-3-BFG/neo/framework/EventLoop.cpp:186
#22 0x000000001038b6c0 in idEventLoop::RunEventLoop(bool) (this=0x11640200 <eventLoopLocal>, commandExecution=true)
    at /home/tle/src/RBDOOM-3-BFG/neo/framework/EventLoop.cpp:221
#23 0x00000000103cc5fc in idCommonLocal::Frame() (this=0x11379d20 <commonLocal>)
    at /home/tle/src/RBDOOM-3-BFG/neo/framework/common_frame.cpp:537
#24 0x0000000010c8ec28 in main(int, char const**) (argc=1, argv=0x7fffffffed08)
    at /home/tle/src/RBDOOM-3-BFG/neo/sys/posix/platform_linux.cpp:617

```

**Comment by runlevel5** [comment]
> @r-a-sattarov Maybe this PR #378 will fix it?

nope, still get segfault
